services:
  db:
    image: postgres:15
    container_name: sensor_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sensor_monitoring_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: sensor_api
    ports:
      - "8000:8000"
    environment:
      # use DATABASE_URL so your Node app can connect
      DATABASE_URL: postgresql://postgres:postgres@db:5432/sensor_monitoring_db
      MQTT_BROKER: mqtt://broker.emqx.io
      MQTT_TOPIC: TEST_CLIMATE_SENSOR_DATA
      MQTT_CLIENT_ID: sensor-monitoring-ingestor
      PORT: 8000
    depends_on:
      - db

volumes:
  pgdata:
